# Generated by Django 4.2.16 on 2026-02-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'article")),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('resume', models.CharField(help_text="Affiché sur la page d'accueil (max 300 caractères)", max_length=300, verbose_name='Résumé court')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Image de couverture')),
                ('icone', models.CharField(default='📰', help_text="Utilisée si pas d'image (ex: 📰 🎥 🚀 🏆)", max_length=10, verbose_name='Icône emoji')),
                ('date_publication', models.DateTimeField(verbose_name='Date de publication')),
                ('publie', models.BooleanField(default=True, verbose_name='Publié')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication'],
            },
        ),
    ]
