# Generated by Django 4.2.16 on 2026-02-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_temoignage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug URL'),
        ),
    ]
